# Generated by Django 3.2.13 on 2022-06-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='next_level_price',
            field=models.IntegerField(default=10),
        ),
    ]
